Create Teensy Sensors interface
EPFLRocketTeam/2024_I_AV_SW_ARCH pull request #23
Opened 2024-03-27 06:17 UTC by phamelink

2024-03-27 06:19 UTC, phamelink commented
@MrZebulon Hey Sam, this is still a work in progress and what I was able to do this morning. Can you quickly check it out just to make sure I'm on the right track ?

2024-04-11 17:16 UTC, MrZebulon requested changes

2024-04-11 17:16 UTC, MrZebulon commented on include/teensy/base_teensy_sensors.hpp
> +    union sensor_calibration_data {
Pour que ça marche bien il est nécéssaire que toutes les structs dans l'union aient la même taille. Il faut réserver des bytes dans bno_calibration_t.


Peut être fait via:
```c++
  #define SENSORS_DATA_SIZE <INSERT SIZE HERE>
  uint8_t reserved[SENSORS_DATA_SIZE - sizeof(float)*2];
```

2024-04-11 17:16 UTC, MrZebulon commented on include/teensy/base_teensy_sensors.hpp
> +template<class I2CInterface, class BNOSensor, class BMPSensor, class GNSSSensor>
Il faut prévoir 3 BNOs et 3 BMPs

2024-04-11 18:06 UTC, MrZebulon approved these changes

2024-04-11 18:06 UTC, merged